<script>
    if (!window.jQuery) {
        document.write('<script src="\/\/ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"><\/script>');
    }
</script>
<?php $_mapsApiKey = Mage::helper('paczkawruchu')->getGoogleMapsApiKey(); ?>
<script type="text/javascript"
        src="//maps.google.com/maps/api/js?key=<?php echo $_mapsApiKey ?>&sensor=true&language=pl&libraries=places&v=3.17.15"></script>

<script>
    var pwr = Object.create(PaczkaWRuchu);

    <?php if($this->getCheckoutType() == 'mage/onepage'): ?>
    var gotoSectionOriginal = Checkout.prototype.gotoSection;
    Checkout.prototype.gotoSection = function (section, reloadProgressBlock) {
        gotoSectionOriginal.call(checkout, section, reloadProgressBlock);
        if (section === 'shipping_method') {
            pwr.initMageOnepage();
        }
    };
    <?php endif; ?>

    <?php if($this->getCheckoutType() == 'iwd/opc4'): ?>
    var validateShippingMethodOriginal = IWD.OPC.Shipping.validateShippingMethod;
    IWD.OPC.Shipping.validateShippingMethod = function () {
        var shippingChecked = validateShippingMethodOriginal();
        return shippingChecked && pwr.validate();
    };

    var prepareAddressResponseOriginal = IWD.OPC.Checkout.prepareAddressResponse;
    IWD.OPC.Checkout.prepareAddressResponse = function (response) {
        prepareAddressResponseOriginal(response);
        pwr.reinitIwdOpc(response);
    };

    var reloadShippingsPaymentsResponseOriginal = IWD.OPC.Checkout.reloadShippingsPaymentsResponse;
    IWD.OPC.Checkout.reloadShippingsPaymentsResponse = function (response) {
        reloadShippingsPaymentsResponseOriginal(response);
        pwr.reinitIwdOpc(response);
    };

    var prepareResponseOriginal = IWD.OPC.Checkout.prepareResponse;
    IWD.OPC.Checkout.prepareResponse = function (response) {
        prepareResponseOriginal(response);
        pwr.reinitIwdOpc(response);
    };

    pwr.initIwdOpc();
    <?php endif; ?>
</script>
